### ISSUE TITLE
Implement webrtc in js-libp2p

### ISSUE THREAD

**Issue by ddimaria** [little-bear-labs/js-libp2p-webrtc#17]
## Tasks

- [X] Skeletons for Transport, Connection, and Stream implementations
- [x] SDP munging
- [X] SDP creation
- [X] Implement Transport.dial
- [x] Implement remainder of Transport
- [x] Implement Connection.newStream
- [x] Implement remainder of Connection
- [x] Implement Stream.source
- [x] Implement Stream.sink
- [x] Implement remainder of Stream
- [ ] Fill out README.md and any other worthwhile documentation
- [X] Unit test SDP utilities
- [ ] Unit test Transport
- [x] Unit test Connection
- [x] Unit test Stream
- [ ] Compliance testing
- [ ] End-to-end test
- [ ] Custom error types
